<?php

namespace ContainerPAja1TT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VESmRujService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VESmRuj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VESmRuj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'answerRepository' => ['privates', '.errored.rfD3CUZ', NULL, 'Cannot determine controller argument for "App\\Controller\\ProductController::popularAnswers()": the $answerRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\AnswerRepository". Did you forget to add a use statement?'],
        ], [
            'answerRepository' => '?',
        ]);
    }
}
