<?php

namespace ContainerPAja1TT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_UkPFHLSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.UkPFHLS' shared service.
     *
     * @return \App\Controller\LoggerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ProductController::answerVote()": the $logger argument is type-hinted with the non-existent class or interface: "App\\Controller\\LoggerInterface". Did you forget to add a use statement?');
    }
}
