<?php

namespace ContainerPAja1TT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LEa6ffService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l_ea6ff' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l_ea6ff'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored.FUHhSRb', NULL, 'Cannot determine controller argument for "App\\Controller\\LoginController::onAuthenticationSuccess()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
            'token' => ['privates', '.errored.P5SF9p3', NULL, 'Cannot determine controller argument for "App\\Controller\\LoginController::onAuthenticationSuccess()": the $token argument is type-hinted with the non-existent class or interface: "App\\Controller\\TokenInterface". Did you forget to add a use statement?'],
        ], [
            'request' => '?',
            'token' => '?',
        ]);
    }
}
