<?php

namespace ContainerPAja1TT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_RfD3CUZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.rfD3CUZ' shared service.
     *
     * @return \App\Controller\AnswerRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ProductController::popularAnswers()": the $answerRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\AnswerRepository". Did you forget to add a use statement?');
    }
}
