<?php

namespace ContainerPAja1TT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_P5SF9p3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.P5SF9p3' shared service.
     *
     * @return \App\Controller\TokenInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\LoginController::onAuthenticationSuccess()": the $token argument is type-hinted with the non-existent class or interface: "App\\Controller\\TokenInterface". Did you forget to add a use statement?');
    }
}
