<?php

namespace ContainerPAja1TT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_INSg9wCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iNSg9wC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iNSg9wC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'answer' => ['privates', '.errored.bHwrOK8', NULL, 'Cannot determine controller argument for "App\\Controller\\ProductController::answerVote()": the $answer argument is type-hinted with the non-existent class or interface: "App\\Controller\\Answer". Did you forget to add a use statement?'],
            'entityManager' => ['privates', '.errored.Ulnstf8', NULL, 'Cannot determine controller argument for "App\\Controller\\ProductController::answerVote()": the $entityManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
            'logger' => ['privates', '.errored.UkPFHLS', NULL, 'Cannot determine controller argument for "App\\Controller\\ProductController::answerVote()": the $logger argument is type-hinted with the non-existent class or interface: "App\\Controller\\LoggerInterface". Did you forget to add a use statement?'],
        ], [
            'answer' => '?',
            'entityManager' => '?',
            'logger' => '?',
        ]);
    }
}
